### ISSUE TITLE
PC Port

### ISSUE THREAD

**Issue by thecozies** [HackerN64/HackerSM64#109] opened 2021-12-11 22:19 UTC
!!!IMPORTANT

**Comment by NyakoFox** [comment] 2021-12-14 19:07
This NEEDS to be on PC Port!

**Comment by Mineqwerty** [comment] 2021-12-15 03:45
This NEEDS to be on PC Port!

**Comment by CrashOveride95** [comment] 2021-12-15 11:09
epic chain break

**Comment by someone2639** [comment] 2021-12-15 11:11
this NEEDS to be on PC Port!

**Comment by Reonu** [comment] 2021-12-15 11:16
this NEEDS to be on PC Port!

**Comment by farisawan-2000** [comment] 2021-12-15 11:26
I personally think the stipulations of a PC Port are a bit out of scope for this repository which aims to be easy for users to modify in  as many ways as possible. If half of the defines set up in `config.h` don't even work on the port, then it creates user confusion as to why an arbitrary feature doesn't work, compared to an emulator or console on which most, if not all, defines are tested. Additionally, distributing a PC Port mod effectively and as legally as possible requires significantly more work than just creating a patch. For these reasons, this Super Mario 64 repository should stay away from a native target that isn't the Nintendo 64, at least until the renderer and hardware abstraction layers are able to be configured with the same defines as console and emulator targets.

**Comment by CrashOveride95** [comment] 2021-12-15 11:27
![bnDvjPk.png](https://user-images.githubusercontent.com/40003130/146178376-7735927c-e207-40c4-b40d-fa700922a91a.png)

**Comment by arthurtilly** [comment] 2021-12-15 11:34
This NEEDS to be on 3DS Port!

**Comment by thecozies** [comment] 2021-12-15 11:40
> I personally think the stipulations of a PC Port are a bit out of scope for this repository, which aims to be easy for users to modify in as many ways as possible. If half of the defines set up in `config.h` don't even work on the port, then it creates user confusion as to why an arbitrary feature doesn't work, compared to an emulator or console on which most, if not all, defines are tested. Additionally, distributing a PC Port mod effectively and as legally as possible requires significantly more work than just creating a patch. For these reasons, this Super Mario 64 repository should stay away from a native target that isn't the Nintendo 64, at least until the renderer and hardware abstraction layers are able to be configured with the same defines as console and emulator targets.

this is legitimately a great argument lmao, i'm convinced

@Reonu should we close this issue forever and ever?

**Comment by Reonu** [comment] 2021-12-15 12:54
damn yeah farisawan convinced me

I had already finished the PC port was gonna PR it but I just can't argue against that

therefore I've permanently deleted all of my PC port related files, the port is cancelled and the issue is closed 😔

**Comment by NyakoFox** [comment] 2022-07-20 16:45
I hope you get banned

**Comment by Reonu** [comment] 2022-07-20 16:47
brb killing pyro

**Comment by BeverlyBean** [comment] 2022-07-20 16:52
> this NEEDS to be on PC port!
![huh-what-did-you-say](https://user-images.githubusercontent.com/105609601/180038990-01b5decf-6c63-4db2-a479-d185534a78b5.gif)

**Comment by axollyon** [comment] 2022-07-20 21:19
![caprisun](https://user-images.githubusercontent.com/20480418/180084058-fc1abd28-e92f-4d0c-8126-f2181cb6e607.gif)

**Comment by Reonu** [comment] 2022-07-20 22:57
This NEEDS to be on PC Port!

**Comment by Arceveti** [comment] 2022-07-20 23:01
This NEEDS to be on PC Port!

**Comment by Reonu** [comment] 2022-07-20 23:03
damn sorry i just read [farisawan-2000](https://github.com/farisawan-2000)'s comment again

**Closed by Reonu** 2022-07-20 23:03 UTC
Labels: bug, documentation, enhancement, help wanted, good first issue, question, wontfix, critical, needs verification, needs console verification, performance, HOW, low priority, high priority, medium priority, monkaS, Lighting Engine

**Comment by Lilaa3** [comment] 2022-07-20 23:05
This NEEDS to be on PC Port!

**Comment by Reonu** [comment] 2022-07-20 23:06
a
